Repository AY2122S1-CS2103T-T09-4/tp, pull requests merged in 2021-11, with the labels that each got.

#203 Bug fixes
  docs/UserGuide.md
  src/main/java/seedu/fast/logic/commands/RemarkCommand.java
  src/main/java/seedu/fast/model/person/Address.java
  src/main/java/seedu/fast/model/person/Appointment.java
  src/main/java/seedu/fast/model/person/Phone.java
  src/main/java/seedu/fast/model/person/Remark.java
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PersonComponent.fxml
  src/main/resources/view/PersonListCard.fxml
  src/main/resources/view/TagComponent.fxml
  src/test/java/seedu/fast/logic/commands/SortCommandTest.java
  src/test/java/seedu/fast/model/person/AddressTest.java
  src/test/java/seedu/fast/model/person/EmailTest.java
  src/test/java/seedu/fast/model/person/LengthUtil.java
  src/test/java/seedu/fast/model/person/NameTest.java
  src/test/java/seedu/fast/model/person/PhoneTest.java
  src/test/java/seedu/fast/model/person/RemarkTest.java
  src/test/java/seedu/fast/testutil/TypicalPersons.java
Labels: type.Task, priority.High

#208 Fix PE-D bugs
  docs/UserGuide.md
  src/main/java/seedu/fast/model/person/Person.java
  src/main/java/seedu/fast/ui/MainWindow.java
  src/main/resources/view/StatsWindow.fxml
Labels: type.Bug, documentation

#212 Update PPP
  docs/team/peiyuan.md
Labels: documentation, priority.Medium

#217 Update DG issues
  docs/DeveloperGuide.md
  docs/diagrams/AppointmentActivityDiagram.puml
  docs/images/AppointmentActivityDiagram.png
  docs/images/LogicClassDiagram.png
  docs/images/UiClassDiagram.png
  src/test/java/seedu/fast/logic/commands/CommandTestUtil.java
  src/test/java/seedu/fast/logic/parser/AppointmentCommandParserTest.java
  src/test/java/seedu/fast/logic/parser/DeleteAppointmentCommandParserTest.java
  src/test/java/seedu/fast/logic/parser/EditAppointmentCommandParserTest.java
  src/test/java/seedu/fast/logic/parser/MarkAppointmentCommandParserTest.java
  src/test/java/seedu/fast/logic/parser/UnmarkAppointmentCommandParserTest.java
Labels: documentation

#224 Update DG & PPP
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/diagrams/HelpCommandActivityDiagram.puml
  docs/diagrams/HelpCommandParsingSequenceDiagram.puml
  docs/diagrams/StatsWindowSequenceDiagram.puml
  docs/images/HelpCommandActivityDiagram.png
  docs/images/HelpCommandParsingSequenceDiagram.png
  docs/images/StatsWindowSequenceDiagram.png
  docs/team/calvin.md
  docs/team/cyn7hius.md
Labels: documentation

#225 Update PPP and code quality
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/team/trash-bin99.md
  docs/team/wangbin.md
  src/main/java/seedu/fast/logic/parser/TagCommandParser.java
Labels: documentation

#226 Update DG class diagram
  docs/diagrams/UiClassDiagram.puml
  docs/images/UiClassDiagram.png
Labels: documentation

#227 Update UG, DG and PPP
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/TagActivityDiagram.puml
  docs/diagrams/TagCommandState1.puml
  docs/diagrams/TagCommandState2.puml
  docs/diagrams/TagSequenceDiagram.puml
  docs/images/TagActivityDiagram.png
  docs/images/TagCommandState1.png
  docs/images/TagCommandState2.png
  docs/images/TagSequenceDiagram.png
  docs/team/trash-bin99.md
  src/main/java/seedu/fast/logic/parser/TagCommandParser.java
  src/test/java/seedu/fast/logic/parser/TagCommandParserTest.java
Labels: documentation

#229 Fix minor bugs in DG
  docs/DeveloperGuide.md
Labels: documentation

#235 UG pdf conversion fixes
  docs/UserGuide.md
  docs/team/th-429b.md
Labels: documentation

#233 Color update
  docs/images/UG-Screenshots/AppointmentUGScreenshot.PNG
  docs/images/UG-Screenshots/MarkAppointmentUGScreenshot.PNG
  docs/images/UiAnnotated.png
  docs/images/addexample.png
  docs/images/deleteexample.png
  docs/images/findAlexDavidResult.png
  docs/images/tagExample2.png
  docs/images/tagExample3.png
  docs/images/tags_overview.png
  src/main/java/seedu/fast/commons/util/Colors.java
  src/main/java/seedu/fast/ui/TagComponent.java
Labels: severity.Low

#228 Update PPP to standardize format
  build.gradle
  docs/team/th-429b.md
  src/main/java/seedu/fast/commons/core/LogsCenter.java
  src/main/java/seedu/fast/ui/TagComponent.java
Labels: type.Task, priority.Medium

#253 Edit PPP
  docs/team/trash-bin99.md
Labels: documentation

#254 Make PPP compact
  docs/team/trash-bin99.md
Labels: documentation
