Repository AY2122S1-CS2103T-T09-4/tp, pull requests merged in 2021-10, with the labels that each got.

#73 Add custom color to tags
  src/main/java/seedu/fast/commons/util/Colors.java
  src/main/java/seedu/fast/ui/PersonCard.java
  src/main/resources/view/DarkTheme.css
Labels: type.Task, priority.Medium

#77 Appointment command
  docs/AboutUs.md
  docs/UserGuide.md
  docs/team/calvin.md
  docs/team/ethan.md
  docs/team/peiyuan.md
  docs/team/tenghon.md
  docs/team/wangbin.md
  src/main/java/seedu/fast/logic/commands/AppointmentCommand.java
  src/main/java/seedu/fast/logic/commands/EditCommand.java
  src/main/java/seedu/fast/logic/commands/RemarkCommand.java
  src/main/java/seedu/fast/logic/parser/AddCommandParser.java
  src/main/java/seedu/fast/logic/parser/AppointmentCommandParser.java
  src/main/java/seedu/fast/logic/parser/CliSyntax.java
  src/main/java/seedu/fast/logic/parser/FastParser.java
  src/main/java/seedu/fast/model/person/Appointment.java
  src/main/java/seedu/fast/model/person/Person.java
  src/main/java/seedu/fast/model/util/SampleDataUtil.java
  src/main/java/seedu/fast/storage/JsonAdaptedPerson.java
  src/main/java/seedu/fast/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonSerializableFastTest/duplicatePersonFast.json
  src/test/data/JsonSerializableFastTest/typicalPersonsFast.json
  src/test/java/seedu/fast/logic/commands/AppointmentCommandTest.java
  src/test/java/seedu/fast/logic/commands/CommandTestUtil.java
  src/test/java/seedu/fast/logic/commands/EditCommandTest.java
  src/test/java/seedu/fast/logic/commands/RemarkCommandTest.java
  src/test/java/seedu/fast/logic/parser/AppointmentCommandParserTest.java
  src/test/java/seedu/fast/logic/parser/FastParserTest.java
  src/test/java/seedu/fast/logic/parser/RemarkCommandParserTest.java
  src/test/java/seedu/fast/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/fast/testutil/PersonBuilder.java
  src/test/java/seedu/fast/testutil/TypicalPersons.java
Labels: type.Task, priority.High

#79 Minor Modification to Appointment Command
  src/main/java/seedu/fast/logic/commands/AppointmentCommand.java
  src/main/java/seedu/fast/logic/parser/AppointmentCommandParser.java
Labels: type.Task, priority.High

#80 Branch update help window
  build.gradle
  src/main/java/seedu/fast/logic/commands/AddCommand.java
  src/main/java/seedu/fast/logic/commands/ClearCommand.java
  src/main/java/seedu/fast/logic/commands/DeleteCommand.java
  src/main/java/seedu/fast/logic/commands/EditCommand.java
  src/main/java/seedu/fast/logic/commands/ExitCommand.java
  src/main/java/seedu/fast/logic/commands/FindCommand.java
  src/main/java/seedu/fast/logic/commands/ListCommand.java
  src/main/java/seedu/fast/logic/commands/RemarkCommand.java
  src/main/java/seedu/fast/logic/commands/SortCommand.java
  src/main/java/seedu/fast/ui/HelpWindow.java
  src/main/resources/view/HelpWindow.fxml
Labels: type.Task, priority.High

#100 Fix bug in SampleDataUtil
  src/main/java/seedu/fast/model/util/SampleDataUtil.java
Labels: severity.Medium

#184 Bug fix from PED
  docs/UserGuide.md
  src/main/java/seedu/fast/commons/core/index/Index.java
  src/main/java/seedu/fast/logic/commands/AppointmentCommand.java
  src/main/java/seedu/fast/logic/commands/DeleteCommand.java
  src/main/java/seedu/fast/logic/commands/EditAppointmentCommand.java
  src/main/java/seedu/fast/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/fast/logic/parser/ParserUtil.java
  src/main/java/seedu/fast/model/person/Appointment.java
  src/test/java/seedu/fast/logic/commands/CommandTestUtil.java
  src/test/java/seedu/fast/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/fast/logic/parser/DeleteCommandParserTest.java
  src/test/java/seedu/fast/logic/parser/FastParserTest.java
  src/test/java/seedu/fast/logic/parser/ParserUtilTest.java
Labels: type.Bug, severity.High

#200 Fix bugs in UG and Tags
  docs/UserGuide.md
  src/main/java/seedu/fast/logic/parser/ParserUtil.java
  src/main/java/seedu/fast/logic/parser/TagCommandParser.java
  src/main/java/seedu/fast/model/tag/InvestmentPlanTag.java
  src/main/java/seedu/fast/model/tag/PriorityTag.java
  src/main/java/seedu/fast/model/tag/Tag.java
Labels: type.Bug
